version: '3.8'

services:
  db-backup:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data:ro
      - ./scripts/db-backup:/scripts
      - db-backups:/backups
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-certificate_verification}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_BACKUP_DIR=/backups
      - DB_BACKUP_RETENTION_DAYS=${DB_BACKUP_RETENTION_DAYS:-7}
      - DB_BACKUP_S3_BUCKET=${DB_BACKUP_S3_BUCKET:-}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
    networks:
      - app-network
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # Install required tools
      apk add --no-cache aws-cli curl

      # Run backup script
      /scripts/backup.sh

      # Verify the most recent backup
      /scripts/verify.sh
      "

volumes:
  postgres-data:
    external: true
  db-backups:
    name: certificate-verification-db-backups

networks:
  app-network:
    external: true